//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataOsoby.OperationsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Osoba", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceUdajeOsoby.Entity")]
    [System.SerializableAttribute()]
    public partial class Osoba : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFDataOsoby.OperationsService.AdresaOsoby AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumNarodeniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriezviskoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFDataOsoby.OperationsService.AdresaOsoby Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumNarodenia {
            get {
                return this.DatumNarodeniaField;
            }
            set {
                if ((this.DatumNarodeniaField.Equals(value) != true)) {
                    this.DatumNarodeniaField = value;
                    this.RaisePropertyChanged("DatumNarodenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Meno {
            get {
                return this.MenoField;
            }
            set {
                if ((object.ReferenceEquals(this.MenoField, value) != true)) {
                    this.MenoField = value;
                    this.RaisePropertyChanged("Meno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priezvisko {
            get {
                return this.PriezviskoField;
            }
            set {
                if ((object.ReferenceEquals(this.PriezviskoField, value) != true)) {
                    this.PriezviskoField = value;
                    this.RaisePropertyChanged("Priezvisko");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdresaOsoby", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceUdajeOsoby.Entity")]
    [System.SerializableAttribute()]
    public partial class AdresaOsoby : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CisloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cislo {
            get {
                return this.CisloField;
            }
            set {
                if ((this.CisloField.Equals(value) != true)) {
                    this.CisloField = value;
                    this.RaisePropertyChanged("Cislo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica {
            get {
                return this.UlicaField;
            }
            set {
                if ((object.ReferenceEquals(this.UlicaField, value) != true)) {
                    this.UlicaField = value;
                    this.RaisePropertyChanged("Ulica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperationsService.IFileOperation")]
    public interface IFileOperation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileOperation/GetDataFromXML", ReplyAction="http://tempuri.org/IFileOperation/GetDataFromXMLResponse")]
        WPFDataOsoby.OperationsService.Osoba[] GetDataFromXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileOperation/GetDataFromXML", ReplyAction="http://tempuri.org/IFileOperation/GetDataFromXMLResponse")]
        System.Threading.Tasks.Task<WPFDataOsoby.OperationsService.Osoba[]> GetDataFromXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileOperation/WriteDataToCSV", ReplyAction="http://tempuri.org/IFileOperation/WriteDataToCSVResponse")]
        void WriteDataToCSV(WPFDataOsoby.OperationsService.Osoba[] ArrayOfOsoba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileOperation/WriteDataToCSV", ReplyAction="http://tempuri.org/IFileOperation/WriteDataToCSVResponse")]
        System.Threading.Tasks.Task WriteDataToCSVAsync(WPFDataOsoby.OperationsService.Osoba[] ArrayOfOsoba);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileOperationChannel : WPFDataOsoby.OperationsService.IFileOperation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileOperationClient : System.ServiceModel.ClientBase<WPFDataOsoby.OperationsService.IFileOperation>, WPFDataOsoby.OperationsService.IFileOperation {
        
        public FileOperationClient() {
        }
        
        public FileOperationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileOperationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPFDataOsoby.OperationsService.Osoba[] GetDataFromXML() {
            return base.Channel.GetDataFromXML();
        }
        
        public System.Threading.Tasks.Task<WPFDataOsoby.OperationsService.Osoba[]> GetDataFromXMLAsync() {
            return base.Channel.GetDataFromXMLAsync();
        }
        
        public void WriteDataToCSV(WPFDataOsoby.OperationsService.Osoba[] ArrayOfOsoba) {
            base.Channel.WriteDataToCSV(ArrayOfOsoba);
        }
        
        public System.Threading.Tasks.Task WriteDataToCSVAsync(WPFDataOsoby.OperationsService.Osoba[] ArrayOfOsoba) {
            return base.Channel.WriteDataToCSVAsync(ArrayOfOsoba);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperationsService.IDataOperation")]
    public interface IDataOperation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataOperation/GetLessAge", ReplyAction="http://tempuri.org/IDataOperation/GetLessAgeResponse")]
        WPFDataOsoby.OperationsService.Osoba[] GetLessAge(WPFDataOsoby.OperationsService.Osoba[] ArrayOfOsoba, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataOperation/GetLessAge", ReplyAction="http://tempuri.org/IDataOperation/GetLessAgeResponse")]
        System.Threading.Tasks.Task<WPFDataOsoby.OperationsService.Osoba[]> GetLessAgeAsync(WPFDataOsoby.OperationsService.Osoba[] ArrayOfOsoba, int age);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataOperationChannel : WPFDataOsoby.OperationsService.IDataOperation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataOperationClient : System.ServiceModel.ClientBase<WPFDataOsoby.OperationsService.IDataOperation>, WPFDataOsoby.OperationsService.IDataOperation {
        
        public DataOperationClient() {
        }
        
        public DataOperationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataOperationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPFDataOsoby.OperationsService.Osoba[] GetLessAge(WPFDataOsoby.OperationsService.Osoba[] ArrayOfOsoba, int age) {
            return base.Channel.GetLessAge(ArrayOfOsoba, age);
        }
        
        public System.Threading.Tasks.Task<WPFDataOsoby.OperationsService.Osoba[]> GetLessAgeAsync(WPFDataOsoby.OperationsService.Osoba[] ArrayOfOsoba, int age) {
            return base.Channel.GetLessAgeAsync(ArrayOfOsoba, age);
        }
    }
}
